# Configuration des services média (images/vidéos)
media_services:
  image_generation:
    provider: comfyui
    workflow: flux_cinemat.json

  image_editing:
    provider: comfyui
    workflow: flux_kontext_master.json

  image_composition:
    provider: comfyui
    workflow: flux_kontext_master.json

  video_generation:
    provider: comfyui
    workflow: wan_video_22.json

# Configuration des services LLM (texte)
llm_services:
  text_generation:
    provider: local_deepseek
    model_path: /home/yopla/montage_models/llm_models/python/models/txt2txt/DeepSeek-R1-Distill-Qwen-14B-Q5_K_S/DeepSeek-R1-Distill-Qwen-14B-Q5_K_S.gguf

  multimodal:
    provider: local_llava
    model_path: /home/yopla/Documents/llm_models/python/models/multimodal/llava-v1.5-13b-Q6_K.gguf
    clip_path: /home/yopla/Documents/llm_models/python/models/multimodal/mmproj-model-f16.gguf

# Configuration des providers
providers:
  comfyui:
    base_path: /home/yopla/Applications/SD/comfyui/ComfyUI/
    url: http://127.0.0.1:8188

  replicate:
    default_models:
      image: bytedance/sdxl-lightning-4step
      video: some-video-model

  local_deepseek:
    n_ctx: 8192
    temperature: 0.6
    max_tokens: 8000

  local_llava:
    n_ctx: 4096
    temperature: 0.7
    max_tokens: 2048